name: DevSecOps Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  # -------------------------
  # 1) SAST Job (SonarCloud)
  # -------------------------
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Shahad2964_shahadhub-todolist
            -Dsonar.organization=shahad2964
            -Dsonar.sources=.

  # -------------------------
  # 2) SCA Job (Dependency-Check)
  # -------------------------
  sca:
    runs-on: ubuntu-latest
    needs: sast
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Dependency-Check (SCA)
        uses: dependency-check/DependencyCheck_Action@main
        with:
          project: "PHP To Do"
          path: "."
          format: "HTML"
          out: "reports"
      - name: Upload SCA Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports

  # -------------------------
  # 3) Staging Environment (Fake HTML)
  # -------------------------
  staging:
    runs-on: ubuntu-latest
    needs: sca
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # إنشاء صفحة HTML فارغة
      - name: Create Dummy HTML
        run: |
          echo "<!DOCTYPE html><html><head><title>Test</title></head><body>Hello</body></html>" > index.html

      - name: Start PHP App (Staging)
        run: |
          php -S 0.0.0.0:8080 -t . &
          sleep 5

      - name: Check Staging
        run: curl -I http://localhost:8080

  # -------------------------
  # 4) DAST Job (ZAP Baseline)
  # -------------------------
  dast:
    runs-on: ubuntu-latest
    needs: staging
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Start Dummy PHP App
        run: |
          echo "<!DOCTYPE html><html><head><title>Test</title></head><body>Hello</body></html>" > index.html
          php -S 0.0.0.0:8080 -t . &
          sleep 5

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: "http://localhost:8080"
          cmd_options: "-r zap-report.html"

      - name: Upload DAST Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html
